import logging
from typing import Any
from fastapi import APIRouter, Depends, HTTPException, status, Query, Response
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
import io

from backend.api.dependencies import get_token_payload, verify_project_access
from backend.database.session import get_db
from backend.models.blueprint import Blueprint
from backend.exports.export import export_compiler
from backend.core.security import decode_token
from backend.core.config import settings

router = APIRouter(prefix="/exports", tags=["Document Exports"])

logger = logging.getLogger("app.exports")


@router.post("/pdf/{project_id}")
@router.get("/pdf/{project_id}")
async def export_pdf(
    project_id: str = Depends(verify_project_access),
    db: AsyncSession = Depends(get_db)
) -> Response:
    """Compiles the startup blueprint into a print-ready A4 document (PDF or print-styled HTML)."""
    import uuid
    project_uuid = uuid.UUID(project_id)
    
    # 1. Fetch unified blueprint
    stmt = select(Blueprint).where(Blueprint.project_id == project_uuid)
    result = await db.execute(stmt)
    blueprint = result.scalars().first()

    if not blueprint:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Unified blueprint has not been composed for this project yet."
        )

    # 2. Try compiling to PDF binary bytes
    pdf_bytes = export_compiler.compile_blueprint_to_pdf(blueprint.data)
    
    if pdf_bytes:
        headers = {
            "Content-Disposition": f"attachment; filename=\"blueprint-{project_id}.pdf\""
        }
        return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)
    
    # 3. Fallback to print-ready HTML
    html_content = export_compiler.compile_blueprint_to_html(blueprint.data)
    headers = {
        "Content-Disposition": f"attachment; filename=\"blueprint-{project_id}.html\""
    }
    return Response(content=html_content, media_type="text/html", headers=headers)


@router.post("/deck/{project_id}")
@router.get("/deck/{project_id}")
async def export_deck(
    project_id: str = Depends(verify_project_access),
    db: AsyncSession = Depends(get_db)
) -> Response:
    """Compiles the startup blueprint into a PowerPoint Pitch Deck presentation (.pptx)."""
    import uuid
    project_uuid = uuid.UUID(project_id)
    
    stmt = select(Blueprint).where(Blueprint.project_id == project_uuid)
    result = await db.execute(stmt)
    blueprint = result.scalars().first()

    if not blueprint:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Unified blueprint has not been composed for this project yet."
        )

    # Compile to PowerPoint (.pptx)
    deck_bytes = export_compiler.compile_blueprint_to_deck(blueprint.data)
    
    if deck_bytes:
        headers = {
            "Content-Disposition": f"attachment; filename=\"pitchdeck-{project_id}.pptx\""
        }
        return Response(
            content=deck_bytes, 
            media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", 
            headers=headers
        )
    
    # Fallback structure containing slides AST
    slides_ast = {
        "success": False,
        "message": "PowerPoint generation failed or library is not available. Here is the structured slide AST.",
        "slides": [
            {
                "title": blueprint.data.get("executive_summary", {}).get("startup_name", "Startup Pitch Deck"),
                "bullets": ["Strategic AI Platform Blueprint", "Generated by Start-up Evolution Engine"]
            }
        ]
    }
    
    if "dna" in blueprint.data:
        slides_ast["slides"].append({
            "title": "Value Proposition & DNA",
            "bullets": [
                f"USP: {blueprint.data['dna'].get('value_proposition', {}).get('core_usp')}",
                f"Revenue Model: {', '.join(blueprint.data['dna'].get('revenue_model', {}).get('revenue_streams', []))}"
            ]
        })
        
    return Response(
        content=str(slides_ast),
        media_type="application/json"
    )


@router.post("/share-link/{project_id}")
async def create_share_link(
    project_id: str = Depends(verify_project_access),
    scope: str = Query("investor:read", description="Access permission scope for the public link"),
    claims: dict[str, Any] = Depends(get_token_payload)
) -> dict[str, Any]:
    """Generates a tokenized public sharing URL with specific access scopes."""
    from jose import jwt as jose_jwt
    from datetime import datetime, timedelta, timezone

    # Generate a long-lived token (e.g., 30 days expiration) for the share scope
    expire = datetime.now(timezone.utc) + timedelta(days=30)
    share_payload = {
        "sub": claims.get("sub"),
        "project_id": project_id,
        "scope": scope,
        "exp": expire,
        "type": "share"
    }
    
    token = jose_jwt.encode(share_payload, settings.SECRET_KEY, algorithm=settings.ALGORITHM)
    share_url = f"/api/v1/blueprints/shared/{token}"
    
    return {
        "success": True,
        "data": {
            "share_token": token,
            "share_url": share_url,
            "scope": scope,
            "expires_at": expire.isoformat()
        },
        "metadata": {
            "api_version": "1.0.0"
        }
    }
